version: '3.4'

services:
  CinemaWorld:
    image: ${DOCKER_REGISTRY-}CinemaWorld
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=password123.
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"